<a href="https://colab.research.google.com/github/rohitjondhalems/Black-Friday-Sale-Prediction/blob/main/Copy_of_Black_Friday_Sale_Prediction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from google.colab import files
uploaded=files.upload()

Saving test.csv to test.csv
Saving train.csv to train.csv


In [3]:
#importing the files
traindata=pd.read_csv('train.csv')
testdata=pd.read_csv('test.csv')

In [4]:
traindata.head()

User_ID Product_ID Gender  ... Product_Category_2  Product_Category_3 Purchase
0  1000001  P00069042      F  ...                NaN                 NaN     8370
1  1000001  P00248942      F  ...                6.0                14.0    15200
2  1000001  P00087842      F  ...                NaN                 NaN     1422
3  1000001  P00085442      F  ...               14.0                 NaN     1057
4  1000002  P00285442      M  ...                NaN                 NaN     7969

[5 rows x 12 columns]

In [5]:
print(traindata.shape)

(550068, 12)


In [6]:
traindata.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [7]:
print(testdata.shape)

(233599, 11)


In [8]:
testdata.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
dtype: object

In [9]:
testdata.head()

User_ID Product_ID  ... Product_Category_2 Product_Category_3
0  1000004  P00128942  ...               11.0                NaN
1  1000009  P00113442  ...                5.0                NaN
2  1000010  P00288442  ...               14.0                NaN
3  1000010  P00145342  ...                9.0                NaN
4  1000011  P00053842  ...                5.0               12.0

[5 rows x 11 columns]

In [10]:
traindata1=traindata.drop('Purchase',axis=1)

In [11]:
print(traindata1.shape)

(550068, 11)


In [12]:
traindata1.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
dtype: object

In [13]:
combinedata=pd.concat([traindata1,testdata],axis=0)

In [14]:
combinedata.head()

User_ID Product_ID  ... Product_Category_2 Product_Category_3
0  1000001  P00069042  ...                NaN                NaN
1  1000001  P00248942  ...                6.0               14.0
2  1000001  P00087842  ...                NaN                NaN
3  1000001  P00085442  ...               14.0                NaN
4  1000002  P00285442  ...                NaN                NaN

[5 rows x 11 columns]

In [15]:
print(combinedata.shape)

(783667, 11)


In [16]:
combinedata.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
dtype: object

In [17]:
combinedata.isnull().sum().sort_values(ascending=False)

Product_Category_3            545809
Product_Category_2            245982
Product_Category_1                 0
Marital_Status                     0
Stay_In_Current_City_Years         0
City_Category                      0
Occupation                         0
Age                                0
Gender                             0
Product_ID                         0
User_ID                            0
dtype: int64

In [18]:
combinedata.Product_Category_3.head()

0     NaN
1    14.0
2     NaN
3     NaN
4     NaN
Name: Product_Category_3, dtype: float64

In [19]:
combinedata.Product_Category_2.head()

0     NaN
1     6.0
2     NaN
3    14.0
4     NaN
Name: Product_Category_2, dtype: float64

In [20]:
#splitting the data accourding to the dtypes
objectdata=combinedata.select_dtypes(include=np.object)
numberdata=combinedata.select_dtypes(include=np.number)

In [21]:
objectdata.head()

Product_ID Gender   Age City_Category Stay_In_Current_City_Years
0  P00069042      F  0-17             A                          2
1  P00248942      F  0-17             A                          2
2  P00087842      F  0-17             A                          2
3  P00085442      F  0-17             A                          2
4  P00285442      M   55+             C                         4+

In [22]:
objectdata.shape

(783667, 5)

In [23]:
numberdata.head()

User_ID  Occupation  ...  Product_Category_2  Product_Category_3
0  1000001          10  ...                 NaN                 NaN
1  1000001          10  ...                 6.0                14.0
2  1000001          10  ...                 NaN                 NaN
3  1000001          10  ...                14.0                 NaN
4  1000002          16  ...                 NaN                 NaN

[5 rows x 6 columns]

In [24]:
numberdata.shape

(783667, 6)

In [25]:
numberdata.isnull().sum().sort_values(ascending=False)

Product_Category_3    545809
Product_Category_2    245982
Product_Category_1         0
Marital_Status             0
Occupation                 0
User_ID                    0
dtype: int64

In [26]:
objectdata.isnull().sum().sort_values(ascending=False)

Stay_In_Current_City_Years    0
City_Category                 0
Age                           0
Gender                        0
Product_ID                    0
dtype: int64

In [27]:
from sklearn.impute import SimpleImputer

In [28]:
si=SimpleImputer(missing_values=np.nan,strategy='mean')

In [29]:
numberdata_impute=si.fit_transform(numberdata)

In [30]:
labels=combinedata.select_dtypes(np.number).columns

In [31]:
numberdatadf=pd.DataFrame(numberdata_impute,columns=labels)

In [32]:
numberdatadf.head()

User_ID  Occupation  ...  Product_Category_2  Product_Category_3
0  1000001.0        10.0  ...            9.844506           12.668605
1  1000001.0        10.0  ...            6.000000           14.000000
2  1000001.0        10.0  ...            9.844506           12.668605
3  1000001.0        10.0  ...           14.000000           12.668605
4  1000002.0        16.0  ...            9.844506           12.668605

[5 rows x 6 columns]

In [33]:
numberdatadf.shape

(783667, 6)

In [34]:
numberdatadf.isnull().sum().sort_values(ascending=False)

Product_Category_3    0
Product_Category_2    0
Product_Category_1    0
Marital_Status        0
Occupation            0
User_ID               0
dtype: int64

In [35]:
objectdata.head()

Product_ID Gender   Age City_Category Stay_In_Current_City_Years
0  P00069042      F  0-17             A                          2
1  P00248942      F  0-17             A                          2
2  P00087842      F  0-17             A                          2
3  P00085442      F  0-17             A                          2
4  P00285442      M   55+             C                         4+

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
le=LabelEncoder()

In [38]:
objectdatadummy=objectdata.apply(le.fit_transform)

In [39]:
objectdatadummy.head()

Product_ID  Gender  Age  City_Category  Stay_In_Current_City_Years
0         684       0    0              0                           2
1        2406       0    0              0                           2
2         868       0    0              0                           2
3         844       0    0              0                           2
4        2769       1    6              2                           4

In [40]:
objectdatadummy.reset_index(drop=True, inplace=True)
numberdatadf.reset_index(drop=True, inplace=True)

In [41]:
processeddata=pd.concat([numberdatadf,objectdatadummy],axis=1)

In [42]:
processeddata.head()

User_ID  Occupation  ...  City_Category  Stay_In_Current_City_Years
0  1000001.0        10.0  ...              0                           2
1  1000001.0        10.0  ...              0                           2
2  1000001.0        10.0  ...              0                           2
3  1000001.0        10.0  ...              0                           2
4  1000002.0        16.0  ...              2                           4

[5 rows x 11 columns]

In [43]:
processeddata.shape

(783667, 11)

In [44]:
processeddata1=processeddata.drop(['User_ID','Product_ID'],axis=1)

In [45]:
processeddata1.head()

Occupation  Marital_Status  ...  City_Category  Stay_In_Current_City_Years
0        10.0             0.0  ...              0                           2
1        10.0             0.0  ...              0                           2
2        10.0             0.0  ...              0                           2
3        10.0             0.0  ...              0                           2
4        16.0             0.0  ...              2                           4

[5 rows x 9 columns]

In [46]:
processed_traindata=processeddata1[:550068]
processed_testdata=processeddata1[550068:]

In [47]:
processed_traindata.shape

(550068, 9)

In [48]:
processed_testdata.shape

(233599, 9)

In [49]:
X=processed_traindata
y=traindata.Purchase

In [50]:
#Fitting the Linear Regression Model
from sklearn.linear_model import LinearRegression

In [51]:
LinReg=LinearRegression()

In [52]:
LinRegmodel=LinReg.fit(X,y)

In [53]:
print(LinRegmodel.intercept_)
print(LinRegmodel.coef_)

10225.000723238401
[   6.41824701  -54.98511539 -406.9157329   -85.62999692   78.45304739
  506.52442396  119.1173629   348.93175804    8.10792913]


In [54]:
LinRegmodel.score(X,y)

0.12861669043689772

In [55]:
from sklearn.model_selection import cross_val_score

In [56]:
cross_val_score(LinRegmodel,X,y,cv=10)

array([0.11381174, 0.10898558, 0.10945578, 0.1061709 , 0.11281999,
       0.1054517 , 0.11473579, 0.10494686, 0.10937609, 0.25498688])

In [57]:
LinRegpedict=LinRegmodel.predict(X)

In [58]:
LinRegResidual=y-LinRegpedict # Residual

In [59]:
np.sqrt(np.mean(LinRegResidual**2)) # RMSE

4688.922514626099

In [60]:
# Predict Dependent Variable in test Data
LinRegtest=LinRegmodel.predict(processed_testdata)

In [61]:
LinRegtest

array([11208.12978232, 11121.72705761,  8675.64144925, ...,
       10992.2583646 ,  6992.83702724,  9965.92627036])

In [62]:
#fitting the Decision Tree Regressor model
from sklearn.tree import DecisionTreeRegressor


In [63]:
treemodel= DecisionTreeRegressor()

In [64]:
treemodel.fit(X,y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [65]:
treemodel.score(X,y)

0.7920112477996549

In [66]:
cross_val_score(treemodel,X,y,cv=10)

array([0.55379651, 0.55595284, 0.5585318 , 0.55394948, 0.55412777,
       0.56646659, 0.56202411, 0.55759308, 0.56020892, 0.61930622])

In [67]:
predict=treemodel.predict(processed_testdata)

In [68]:
predict

array([19576.        , 10677.        ,  8357.22222222, ...,
       15622.        , 23714.        ,  2091.        ])

In [69]:
pd.DataFrame(predict).to_csv('Black_Friday_Reg.csv')

In [70]:
import xgboost as xgb

In [71]:
from xgboost import XGBRegressor

In [72]:
xgbr=XGBRegressor()

In [73]:
xgbr.fit(X,y)

[09:34:15] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [74]:
xgbr.score(X,y)

0.6480162897888689

In [75]:
cross_val_score(xgbr,X,y,cv=10)

[09:34:34] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:34:49] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:35:04] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:35:19] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:35:34] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:35:49] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:36:04] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[09:36:19] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of re

array([0.6381077 , 0.63764766, 0.6391078 , 0.63862871, 0.63923834,
       0.64063841, 0.64228298, 0.63704433, 0.640038  , 0.68342909])

In [76]:
xgbr_predict=xgbr.predict(X)

In [77]:
print(xgbr_predict)

[10004.255   12994.981    1529.9045  ...   803.55585   517.08295
   795.17145]


In [78]:
xgbr_predict_test=xgbr.predict(processed_testdata)

In [79]:
print(xgbr_predict_test)

[13200.379  10204.432   6131.8247 ... 12741.63   18478.395   2667.407 ]


In [80]:
pd.DataFrame(xgbr_predict_test).to_csv('Black_Friday_Reg1.csv')

In [81]:
from google.colab import files
files.download('Black_Friday_Reg1.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>